"""Added url column in User table

Revision ID: 401915b20303
Revises: 95a411e4aeee
Create Date: 2021-03-31 17:02:19.294333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "401915b20303"
down_revision = "95a411e4aeee"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "url")
    # ### end Alembic commands ###
