"""added spotify auth column

Revision ID: d12a3744e77f
Revises: 401915b20303
Create Date: 2021-03-31 18:05:58.199833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d12a3744e77f"
down_revision = "401915b20303"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("spotify_auth", sa.String(), nullable=True))
    op.drop_column("user", "url")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("url", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_column("user", "spotify_auth")
    # ### end Alembic commands ###
